package sample.oracle.otn.soascheduler.proxy;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

public class HelloWorldProcess_ptClient
{
  @WebServiceRef
  private static Helloworldprocess_client_ep helloworldprocess_client_ep;

  public static void main(String [] args)
  {
    helloworldprocess_client_ep = new Helloworldprocess_client_ep();
    HelloWorldProcess helloWorldProcess = helloworldprocess_client_ep.getHelloWorldProcess_pt();
    // Add your code to call the desired methods.
    System.out.println(helloWorldProcess.process("SOAScheduler"));
  }
}
