package com.oracle.xmlns.payments_api_enablement.paymentscustomervalidation.paymentscustomervalidationbpelprocess;

import com.oracle.xmlns.paymentenablement_soa.paymentbookingprocess.bankpaymentbookingprocess.BankPaymentBookingProcess;
import com.oracle.xmlns.paymentenablement_soa.paymentbookingprocess.bankpaymentbookingprocess.BankpaymentbookingprocessClientEp;

import java.math.BigInteger;

import org.bank.payments.PaymentRequest;
import org.bank.payments.PaymentValidationResponse;

import org.gringottbank.oracle.demo.PaymentBookingRequest;
import org.gringottbank.oracle.demo.PaymentBookingResponse;

// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class PaymentsCustomerValidationBPELProcess_ptClient {
    public static void main(String[] args) {
        PaymentscustomervalidationbpelprocessClientEp paymentscustomervalidationbpelprocessClientEp =
            new PaymentscustomervalidationbpelprocessClientEp();
        PaymentsCustomerValidationBPELProcess paymentsCustomerValidationBPELProcess =
            paymentscustomervalidationbpelprocessClientEp.getPaymentsCustomerValidationBPELProcessPt();
        // Add your code to call the desired methods.
        PaymentRequest payload = new PaymentRequest();
        payload.setCustomerID("100");
        payload.setFinTechID("InnerCircleCars");
        payload.setPaymentAmount(6000);
        payload.setPaymentCategory("Cars");
        payload.setPaymentRequestId(BigInteger.valueOf(29));
        payload.setRegion("EMEA");
        payload.setSalesChannel("FinTech");
        payload.setTechnicalChannel("API");
        PaymentValidationResponse response = paymentsCustomerValidationBPELProcess.process(payload);

        System.out.println(response.getPaymentValidationStatus());
        System.out.println(response.getCustomerAsset());
        System.out.println(response.getLoanAmount());

        BankpaymentbookingprocessClientEp bankpaymentbookingprocessClientEp = new BankpaymentbookingprocessClientEp();
        BankPaymentBookingProcess bankPaymentBookingProcess =
            bankpaymentbookingprocessClientEp.getBankPaymentBookingProcessPt();

        PaymentBookingRequest finalReq = new PaymentBookingRequest();
        finalReq.setCustomerAsset(response.getCustomerAsset());
        finalReq.setCustomerID("100");
        finalReq.setFinTechID("InnerCircleCars");
        finalReq.setLoanAmount(response.getLoanAmount());
        finalReq.setPaymentCategory("Cars");
        finalReq.setPaymentID(BigInteger.valueOf(29));
        finalReq.setRegion("EMEA");
        finalReq.setSalesChannel("FinTech");
        finalReq.setTechnicalChannel("API");
        PaymentBookingResponse finalResp = bankPaymentBookingProcess.process(finalReq);

        System.out.println("FinalResponse : " + finalResp.getPaymentBookingStatus());
    }
}
