package com.oracle.xmlns.paymentenablement_soa.paymentbookingprocess.bankpaymentbookingprocess;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class BankPaymentBookingProcess_ptClient {
    public static void main(String[] args) {
        BankpaymentbookingprocessClientEp bankpaymentbookingprocessClientEp = new BankpaymentbookingprocessClientEp();
        BankPaymentBookingProcess bankPaymentBookingProcess =
            bankpaymentbookingprocessClientEp.getBankPaymentBookingProcessPt();
        // Add your code to call the desired methods.


    }
}
