
package com.oracle.xmlns.paymentenablement_soa.paymentbookingprocess.bankpaymentbookingprocess;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bankpaymentbookingprocess_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/PaymentEnablement_SOA/PaymentBookingProcess/BankPaymentBookingProcess",
                  wsdlLocation =
                  "http://oa8102.us.oracle.com:8001/PaymentProcessingAPI/1?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPaymentEnablement_SOA%2FPaymentBookingProcess%2FBankPaymentBookingProcess%7Dbankpaymentbookingprocess_client_ep")
public class BankpaymentbookingprocessClientEp extends Service {

    private final static URL BANKPAYMENTBOOKINGPROCESSCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BANKPAYMENTBOOKINGPROCESSCLIENTEP_EXCEPTION;
    private final static QName BANKPAYMENTBOOKINGPROCESSCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/PaymentEnablement_SOA/PaymentBookingProcess/BankPaymentBookingProcess",
                  "bankpaymentbookingprocess_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://oa8102.us.oracle.com:8001/PaymentProcessingAPI/1?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPaymentEnablement_SOA%2FPaymentBookingProcess%2FBankPaymentBookingProcess%7Dbankpaymentbookingprocess_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKPAYMENTBOOKINGPROCESSCLIENTEP_WSDL_LOCATION = url;
        BANKPAYMENTBOOKINGPROCESSCLIENTEP_EXCEPTION = e;
    }

    public BankpaymentbookingprocessClientEp() {
        super(__getWsdlLocation(), BANKPAYMENTBOOKINGPROCESSCLIENTEP_QNAME);
    }

    public BankpaymentbookingprocessClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKPAYMENTBOOKINGPROCESSCLIENTEP_QNAME, features);
    }

    public BankpaymentbookingprocessClientEp(URL wsdlLocation) {
        super(wsdlLocation, BANKPAYMENTBOOKINGPROCESSCLIENTEP_QNAME);
    }

    public BankpaymentbookingprocessClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKPAYMENTBOOKINGPROCESSCLIENTEP_QNAME, features);
    }

    public BankpaymentbookingprocessClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankpaymentbookingprocessClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BankPaymentBookingProcess
     */
    @WebEndpoint(name = "BankPaymentBookingProcess_pt")
    public BankPaymentBookingProcess getBankPaymentBookingProcessPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/PaymentEnablement_SOA/PaymentBookingProcess/BankPaymentBookingProcess",
                                       "BankPaymentBookingProcess_pt"), BankPaymentBookingProcess.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankPaymentBookingProcess
     */
    @WebEndpoint(name = "BankPaymentBookingProcess_pt")
    public BankPaymentBookingProcess getBankPaymentBookingProcessPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/PaymentEnablement_SOA/PaymentBookingProcess/BankPaymentBookingProcess",
                                       "BankPaymentBookingProcess_pt"), BankPaymentBookingProcess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKPAYMENTBOOKINGPROCESSCLIENTEP_EXCEPTION != null) {
            throw BANKPAYMENTBOOKINGPROCESSCLIENTEP_EXCEPTION;
        }
        return BANKPAYMENTBOOKINGPROCESSCLIENTEP_WSDL_LOCATION;
    }

}
