
package com.oracle.xmlns.paymentenablement_soa.paymentbookingprocess.bankpaymentbookingprocess;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import org.gringottbank.oracle.demo.ObjectFactory;
import org.gringottbank.oracle.demo.PaymentBookingRequest;
import org.gringottbank.oracle.demo.PaymentBookingResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "BankPaymentBookingProcess",
            targetNamespace =
            "http://xmlns.oracle.com/PaymentEnablement_SOA/PaymentBookingProcess/BankPaymentBookingProcess")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BankPaymentBookingProcess {


    /**
     *
     * @param payload
     * @return
     *     returns org.gringottbank.oracle.demo.PaymentBookingResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "paymentBookingResponse", targetNamespace = "http://www.demo.oracle.gringottBank.org",
               partName = "payload")
    public PaymentBookingResponse process(@WebParam(name = "paymentBookingRequest",
                                                    targetNamespace = "http://www.demo.oracle.gringottBank.org",
                                                    partName = "payload") PaymentBookingRequest payload);

}
